server {
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    server_name app.local;
    root /var/www;

    gzip on;
    gzip_types text/plain application/javascript application/json;

    client_max_body_size 50M;

    location ~ /\.ht {
            deny all;
    }
    location ~ composer.json {
            deny all;
    }
    location ~ auth.json {
            deny all;
    }
    
    location ~ (.+)\.php(/|$) {
        set $script $uri;

        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $document_root/public/$script;
    }

    location ~ /(?P<staticfile>.*\.(css|js|png|jpg|gif|html|woff|ttf))$ {

        try_files /public/$staticfile /$staticfile @assetmanager;
    }

    location @assetmanager {

        rewrite ^(.*)$ /index.php last;

        index index.php;
        if (-f $request_filename) {
                break;
        }
    }

    location / {
            alias /var/www/public;
            index index.php;
            if (-f $request_filename) {
                    break;
            }
            rewrite ^(.*)$ /index.php last;
    }
}